# Generated by Django 4.1.3 on 2022-12-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=200)),
                ('country_origin', models.CharField(max_length=100)),
                ('year_formed', models.IntegerField()),
                ('soundcloud_band_url', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('tracks', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('band_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.band')),
            ],
        ),
    ]
