# Generated by Django 4.1.3 on 2022-12-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamart', '0002_bandmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('album_url', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('band_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.band')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_likes', models.IntegerField()),
                ('album_reposts', models.IntegerField()),
                ('album_release_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.bandalbum')),
            ],
        ),
    ]
